# fly.toml app configuration file generated for photo-portfolio-manager on 2023-12-13T02:41:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "photo-portfolio-manager"
primary_region = "iad"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_NAME = "L-Dragon Photography"
  APP_ENV = "production"
  APP_URL = "https://photo-portfolio-manager.fly.dev"
  APP_DEBUG = "true"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "file"
  SESSION_LIFETIME = "120"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION = "sqlite"
  DB_DATABASE = "/var/www/html/storage/database/database.sqlite"
  DB_FOREIGN_KEYS = "true"
  FILESYSTEM_DRIVER = "s3"
  MEDIA_DISK = "s3"
  MAIL_MAILER = "sendmail"
  MAIL_HOST = "localhost"
  MAIL_ENCRYPTION = "null"
  MAIL_FROM_ADDRESS = "me@joseph-oh.com"
  MAIL_FROM_NAME = "L-Dragon Photography"
  AWS_DEFAULT_REGION = "us-east-1"
  AWS_BUCKET = "ldragonphotographymedia"
  AWS_URL = "https://ldragonphotographymedia.s3.amazonaws.com/"
  AWS_USE_PATH_STYLE_ENDPOINT = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "storage_vol"
  destination = "/var/www/html/storage"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
